### ISSUE TITLE
availability - Effects when used is too specific to current UIs

### ISSUE THREAD

**Issue by birgander** [Prisjakt/feed-specification#14]
https://schema.prisjakt.nu/docs/fields/availability/ says:

> EFFECTS WHEN USED
> Will visually (green, yellow, red) indicate if a customer can order the product

I think this is to specific to how the UIs currently indicate availability. It might very well change in the future, in some front end application.

**Comment by andrejohansson** [comment]
How about 

> Enables us to indicate if a customer can order the product

**Comment by birgander** [comment]
Yeah, that’s better!
