### ISSUE TITLE
Wocommerce -> WooCommerce

### ISSUE THREAD

**Issue by birgander** [Prisjakt/feed-specification#26]
**What type of issue**
Spelling mistake

**Describe the issue**
WooCommerce is called Wocommerce in the documentation.

**Location**
https://schema.prisjakt.nu/types-of-feeds/integrations/ talks about Wocommerce, but it's called WooCommerce.

**Suggested solution**
Substitute all instances of Wocommerce with WooCommerce.

**Comment by andrejohansson** [comment]
Fixed in https://github.com/Prisjakt/feed-specification/pull/31
