### ISSUE TITLE
Missing descriptions or explanatin if size fields

### ISSUE THREAD

**Issue by ylvarw** [Prisjakt/feed-specification#40]
1. Other

**Describe the issue**
size and related fields is missing descriptions about field connections and rellations to fashion and shoes category (and no other categories at the moment)

**Location**
[size](https://schema.prisjakt.nu/fields/size#description) 
[size system](https://schema.prisjakt.nu/fields/size_system/#description) 
[age group](https://schema.prisjakt.nu/fields/age_group)
[gender](https://schema.prisjakt.nu/fields/gender/)

**Suggested solution**
add to descriptions that this is only rellevant för fashion and shoes
and related fields is only available if you use size

**Screenshots**
from article in help center:
![image](https://user-images.githubusercontent.com/21193227/227888359-896f17c0-1766-406a-9cf8-11797cd6881c.png)

missing dependency to "Size"
![image](https://user-images.githubusercontent.com/21193227/227888681-56528bfe-38f7-436f-a15d-89858c0e03a4.png)
![image](https://user-images.githubusercontent.com/21193227/227889285-a0b6e37a-17d7-44b8-a782-512da07d8dc6.png)
![image](https://user-images.githubusercontent.com/21193227/227889431-2fc407ea-4026-4433-b065-42da337a2429.png)

**Comment by andrejohansson** [comment]
Fixed in internal MR 626 and awaits deployment.
