### ISSUE TITLE
Wrong info in the property list for product_type

### ISSUE THREAD

**Issue by thornminator** [Prisjakt/feed-specification#42]
**What type of issue**
Factual error

**Describe the issue**
We state in the property list that product_type is not repeatable, even though it is, also as stated in the examples.

**Location**
https://schema.prisjakt.nu/fields/product_type/#properties

**Suggested solution**
Correct the vaule "False" to "True"

**Comment by andrejohansson** [comment]
Fixed in internal MR 626 and awaits deployment.
