### ISSUE TITLE
missing Auth page option OAuth

### ISSUE THREAD

**Issue by ylvarw** [Prisjakt/feed-specification#51]
**What type of issue**
Please pick one of

1. Other

**Describe the issue**
missing OAuth as a auth option

**Location**
https://schema.prisjakt.nu/infrastructure/auth/

1. Go to the nearest headline of the problem
1. Right click and pick *copy link*
1. Paste the link here
(https://schema.prisjakt.nu/infrastructure/auth/)

**Comment by kamilglod** [comment]
We're not supporting oAuth auth method. Closing

**Comment by andrejohansson** [comment]
We support some form of client credentials, we should probably add that?

**Comment by andrejohansson** [comment]
Closing again as the only client credential we supported was a shop specific case.
